# Generated by Django 3.1.7 on 2021-04-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=80)),
                ('customer_surname', models.CharField(max_length=80)),
                ('customer_doc_type', models.CharField(default='CC', max_length=30)),
                ('customer_document', models.CharField(max_length=32)),
                ('customer_email', models.CharField(max_length=120)),
                ('customer_mobile', models.CharField(max_length=40)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(default='', max_length=60)),
                ('process_url', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
